### PR TITLE
test(pact_matching): Test Values matcher with json body

### PR DESCRIPTION
**Pull request by tienvx**
These tests describe weird behavior of `Values` matcher mentioned in #337

* The `Values` matcher is mentioned 2 times in the [specification](https://github.com/pact-foundation/pact-specification/tree/version-4#supported-matching-rules)
  * About `Values` matcher itself: `Match the values in a map, ignoring the keys`
  * About `EachValue` matcher: `... For maps, delgates to the Values matcher.`
* I have no clue how it should work, except it `ignoring the keys`
* I take a look at the code
  * The code handling matching for `maps` and `lists` is a bit complicated.
  * But I can see the `first value` play an important role. It explain why `missing values` is ok, `duplicated first value` is ok
  * Look like the code for `Values` matcher is empty, so it's not implemented, but rely on a general code that handle matching for `maps` and `lists`? I'm not sure.
  * It doesn't `ignore the keys` at the moment.

So I came up with my own "rules" for this matcher (already in the issue above):

For **lists**/json array/array without keys:

1. All values must be present
2. The order of values is not important
3. Missing values are NOT OK
4. Additional values are NOT OK
5. Duplicated values may be OK?

For **maps**/json object/array with keys:

1. Keys must be ignored
2. Other than that, same with lists

 **I don't know how to implement these rules in the code yet when they are accepted.**

Compare with other matchers:

| Behavior   |      Values      | ArrayContains | EachValue |
|----------|:-------------:|------:|------:|
| ignore keys | yes | yes | yes |
| support value's matching rules |  no | yes | yes |
| value's order | not important | not important | not important |
| missing values |not ok | not ok | not sure the behavior when actual values is an empty list/array, not ok I guess |
| additional values |not ok | ok | not ok |
| duplicated values |ok | ok | ok |

### CODE REVIEW

**Comment by rholshausen** [comment]
This is not true:
> The order of values is not important
How can you ensure this? Basically, the Values matcher converts a map into a list of values, and then lets the normal matching logic continue as if a Type matcher was specified. If the order of the values changes, the matching will fail if there are different types. For anything other than a map, it just acts like a Type matcher.

This matcher has been superseded by the EachValue and EachKey matchers, as the logic to implement it was very messy and those two matchers are much clearer on what they do.

**Comment by tienvx** [comment]
> How can you ensure this? Basically, the Values matcher converts a map into a list of values, and then lets the normal matching logic continue as if a Type matcher was specified. If the order of the values changes, the matching will fail if there are different types. For anything other than a map, it just acts like a Type matcher.

Is it really `Type` matcher? I think it's `Equality` matcher

**Comment by tienvx** [comment]
I'm still confused about `Values` matcher.

> This matcher has been superseded by the EachValue and EachKey matchers, as the logic to implement it was very messy and those two matchers are much clearer on what they do.

Should I simply just remove the `Values` matcher from `pact-php` so we don't allow user to use it, so we don't have to maintain it?

cc @mefellows , @YOU54F

**Comment by tienvx** [comment]
Look like `pact-js` has a similar approach recently: deprecated `eachKeyLike` (really `values` matcher) and replace it with `eachKey` and `eachValue`

**Pull request merged**
