### PR TITLE
feat: allow non deafult json content-type

### PR DESCRIPTION
**Pull request by leonasa**

### CODE REVIEW

**Comment by leonasa** [comment]
When using any other type than application/json in pactffi_with_body the match does not work #234

**Comment by rholshausen** [comment]
Thanks for the PR!

**Comment by mefellows** [comment]
Would this change help with #224?

**Comment by leonasa** [comment]
@mefellows it is definitely the same thing. And it will help your case.

**Comment by mefellows** [comment]
Awesome - thank you!

**Pull request merged**
